server:
  port : 8000
spring:
  devtools:
    livereload:
      enabled : true
  datasource:
    url : jdbc:mysql://localhost:3306/rollin?serverTimezone=UTC&characterEncoding=UTF-8
    username : root
    password : 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'


jwt:
  secret_key: SECRET_APPLESECRET_APPLESECRET_APPLESECRET_APPLE
  expTime: 86400000

